export const FETCH_SEARCHED_MOVIE = "FETCH_SEARCHED_MOVIE";
export const FETCH_SEARCHED_MOVIE_SUCCESS = "FETCH_SEARCHED_MOVIE_SUCCESS";
export const FETCH_SEARCHED_MOVIE_FAILURE = "FETCH_SEARCHED_MOVIE_FAILURE";

export const OVERVIEW_SELECTED_MOVIE = "OVERVIEW_SELECTED_MOVIE";
export const OVERVIEW_SELECTED_SUCCESS = "OVERVIEW_SELECTED_SUCCESS";
export const OVERVIEW_SELECTED_FAILURE = "OVERVIEW_SELECTED_FAILURE";

export const VIDEO_SELECTED_MOVIE = "VIDEO_SELECTED_MOVIE";
export const VIDEO_SELECTED_SUCCESS = "VIDEO_SELECTED_SUCCESS";
export const VIDEO_SELECTED_FAILURE = "VIDEO_SELECTED_FAILURE";

export const FETCH_SELECTED_ACTOR = "FETCH_SELECTED_ACTOR";
